#!/usr/bin/env bash

# vim:
ln -s ~/.dotfiles/init.vim ~/.config/nvim

# zsh:
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/.config/zsh/powerlevel10k
ln -s ~/.dotfiles/zsh/.p10k.zsh ~/.p10k.zsh

git clone https://github.com/zsh-users/zsh-autosuggestions ~/.config/zsh/zsh-autosuggestions

git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.config/zsh/zsh-syntax-highlighting

# fzf (can be used with zsh, tmux, nvim. I currently use with zsh)
#mkdir ~/.config/fzf
git clone --depth=1 https://github.com/junegunn/fzf ~/.config/fzf
cd ~/.config/fzf
./install --no-update-rc --no-bash --no-fish

