#!/usr/bin/env bash

# vim:
pip3 install pynvim
mkdir -p ~/.config/nvim/lua/user
ln -s ~/.dotfiles/nvim/init.vim ~/.config/nvim/init.vim
ln -s ~/.dotfiles/nvim/lua/colorscheme.lua ~/.config/nvim/lua/user/colorscheme.lua
ln -s ~/.dotfiles/nvim/lua/keymaps.lua ~/.config/nvim/lua/user/keymaps.lua
ln -s ~/.dotfiles/nvim/lua/nvim-tree.lua ~/.config/nvim/lua/user/nvim-tree.lua
ln -s ~/.dotfiles/nvim/lua/cmp.lua ~/.config/nvim/lua/user/cmp.lua

# zsh:
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/.config/zsh/powerlevel10k
ln -s ~/.dotfiles/zsh/.p10k.zsh ~/.p10k.zsh

git clone https://github.com/zsh-users/zsh-autosuggestions ~/.config/zsh/zsh-autosuggestions

git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.config/zsh/zsh-syntax-highlighting

ln -s ~/.dotfiles/zsh/.zshrc ~/.zshrc

# fzf (can be used with zsh, tmux, nvim. I currently use with zsh)
#mkdir ~/.config/fzf
git clone --depth=1 https://github.com/junegunn/fzf ~/.config/fzf
cd ~/.config/fzf
./install --no-update-rc --no-bash --no-fish

