#!/usr/bin/env bash

# edit dnf config
sudo sh -c 'echo "fastestmirror=True" >>/etc/dnf/dnf.conf'
sudo sh -c 'echo "max_parallel_downloads=10" >>/etc/dnf/dnf.conf'
sudo sh -c 'echo "defaultyes=True" >>/etc/dnf/dnf.conf'

sudo dnf upgrade --refresh

# install g++ (needed for treesitter compilations)
sudo dnf install gcc-c++

# install rust and cargo
sudo dnf install rust cargo

# install fnm for managing node versions
curl -fsSL https://fnm.vercel.app/install | bash -s -- --skip-shell
echo '' >>~/.zshrc_local
echo '# fnm' >>~/.zshrc_local
echo 'export PATH='$HOME/.fnm':$PATH' >>~/.zshrc_local
echo 'eval "`fnm env`"' >>~/.zshrc_local

# install node
fnm install 18.7.0

# install zsh
if ! zsh --version; then
    sudo dnf install zsh
fi

# install recommended nerd font for powerlevel10k
# for more info, see:
# https://github.com/romkatv/powerlevel10k#meslo-nerd-font-patched-for-powerlevel10k
mkdir -p ~/.local/share/fonts
cd ~/.local/share/fonts
curl -fLo "MesloLGS NF Regular.ttf" https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf
curl -fLo "MesloLGS NF Bold.ttf" https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf
curl -fLo "MesloLGS NF Italic.ttf" https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf
curl -fLo "MesloLGS NF Bold Italic.ttf" https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf
cd -

# install neovim
sudo dnf install -y neovim python3-neovim
npm install -g neovim

# install telescop dependencies
#   (ripgrep needed by telescope live_grep)
#   (fd needed by telescope file search)
sudo dnf install ripgrep
sudo dnf install fd-find

# install lazygit (via cool other package repo, for now)
sudo dnf copr enable atim/lazygit -y
sudo dnf install lazygit

# install imwheel configuration (for faster mouse scrolling)
ln -s ~/.dotfiles/misc/.imwheelrc ~/.imwheelrc
ln -s ~/.dotfiles/misc/imwheel.desktop ~/.config/autostart/imwheel.desktop

# install vscode
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
sudo dnf install code

sudo dnf install tree
